# .github/workflows/publish-gatsby-to-github-pages.yml

# Credit https://medium.com/better-programming/deploy-your-gatsby-site-with-github-actions-e761ea93813f
# https://github.com/enriikke/gatsby-gh-pages-action/blob/main/README.md
name: Publish Gatsby to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@v2

      - name: Override SiteConfig.js
        if: github.repository_owner != 'dotnetthailand'
        # Create your base64 file content with `cat data/SiteConfig.js | base64`.
        # More details about new line issue https://stackoverflow.com/a/15490765/1872200
        run: |
          echo "${{ secrets.BASE64_SITE_CONFIG }}" | base64 -di > data/SiteConfig.js 

      # https://github.com/enriikke/gatsby-gh-pages-action/releases
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          # access-token is a GitHub personal access token with the "public_repo" scope.
          # Go to https://github.com/settings/tokens and click "Generate new token" button.
          # Check public_repo.
          # Enter note and expiration.
          # Click "Generate token"
          access-token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          deploy-branch: gh-pages
